### ISSUE TITLE
bcl2fastq, all the fastq files are of zero size

### ISSUE THREAD

**Issue by sambhav2mishra** [brwnj/bcl2fastq#11]
Hello,
When i try to demultiplex using bcl2fastq, the process ran successfully but outputting **process got completed with zero error and 0 warnings**. But all the fastq files have **0 size**. All the reads went undetermined.
Details:
**8 samples, single-end**
what could be the reason?

**Comment by brwnj** [comment]
fwiw, this is the default behavior of illumina's bcl2fastq tool when your barcodes have 0 matches.
